### ISSUE TITLE
Crash while saving a screenshot

### ISSUE THREAD

**Issue by tsujan** [lxde/lximage-qt#87]
lximage-qt crashed while saving a screenshot taken by it:
````
#0  0x00007f598cce78b0 in fm_file_info_get_path () at /usr/lib/libfm.so.4
#1  0x00007f598ccea32f in  () at /usr/lib/libfm.so.4
#2  0x00007f598c6f8f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#3  0x00007f598c70af82 in  () at /usr/lib/libgobject-2.0.so.0
#4  0x00007f598c713bcc in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#5  0x00007f598c713faf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f598ccfba30 in  () at /usr/lib/libfm.so.4
#7  0x00007f598c42043a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#8  0x00007f598c4207f0 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007f598c42089c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#10 0x00007f598b04946f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#11 0x00007f598aff2e9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#12 0x00007f598affb39c in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#13 0x00000000004111e1 in  ()
#14 0x00007f598e2b0291 in __libc_start_main () at /usr/lib/libc.so.6
#15 0x00000000004116fa in _start ()
````
The crash didn't happen afterward. It should be random and rare. It's probably a bug in libfm.

**Comment by tsujan** [comment]
This is very similar to https://github.com/lxde/pcmanfm-qt/issues/397#issuecomment-250975990. The PR https://github.com/lxde/libfm/pull/19 fixed most related crashes for me (I've had no crash in pcmanfm-qt since using it) but, as mentioned there, that commit is a hack rather than a nice solution. As @PCMan told at https://github.com/lxde/pcmanfm-qt/issues/397#issuecomment-261687164, a real solution may require adding of a thread join operation to libfm finalization process. @PCMan?

**Comment by tsujan** [comment]
If anyone is interested, the crash can be reproduced in pcmanfm-qt as explained [here](https://github.com/lxde/pcmanfm-qt/issues/397#issuecomment-261724490) (provided that https://github.com/lxde/libfm/pull/19 isn't applied).

**Comment by tsujan** [comment]
This was automatically fixed by libfm-qt's C++11 port a long time ago. Closing.
